#!/bin/bash

start_time=$(date +%s)

# Commands
sleep 3665

end_time=$(date +%s)

total_time=$((end_time - start_time))

hours=$((total_time / 3600))
minutes=$(((total_time % 3600) / 60))
seconds=$((total_time % 60))

echo "Total execution time: ${hours}h ${minutes}m ${seconds}s"
